export const EXAMPLE_RATING = 6
export const MIN_RATING = 1
export const MAX_RATING = 12
export const TIMING = {
  OUTER_TIMEOUT: 1000,
  INNER_TIMEOUT: 300,
  APPROVAL_DELAY: 500,
  DESTROY_APP_DELAY: 1000,
  DESTROY_TOAST_APP_DELAY: 3000,
}
